CAMERA_ID = 0
FRAME_WIDTH = 640
FRAME_HEIGHT = 480

YOLO_MODEL_FILENAME = 'seu_modelo_yolo.tflite'
CNN_MODEL_FILENAME = 'seu_modelo_cnn.tflite'
MODELS_DIR = 'models'

YOLO_INPUT_SIZE = (256, 256) 
CNN_INPUT_SIZE = (128, 128)

CNN_CLASSES = ['25', '35', '45', '55', '65', '75', '85', '95']

YOLO_CONFIDENCE_THRESHOLD = 0.3
CNN_CONFIDENCE_THRESHOLD = 0.6
PIN_AQUECEDOR = 17
PIN_VENTOINHA = 18
PIN_MOTOR_TAMBOR = 27

ESTAGIO_FINAL_DESEJADO = 'full_city'

BASE_DATASET_PATH = 'dataset/train'
CNN_TRAIN_DATA_PATH = f'{BASE_DATASET_PATH}/cnn_data'
YOLO_TRAIN_IMAGES_PATH = f'{BASE_DATASET_PATH}/yolo_data/images'
YOLO_TRAIN_LABELS_PATH = f'{BASE_DATASET_PATH}/yolo_data/labels'

TRAIN_BATCH_SIZE = 16
TRAIN_EPOCHS_CNN = 20
TRAIN_EPOCHS_YOLO = 50
TRAIN_LEARNING_RATE = 0.001